# Generated by Django 3.1.4 on 2021-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.AddField(
            model_name='content',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Je koncept?'),
            preserve_default=False,
        ),
    ]
