# Generated by Django 3.1.4 on 2020-12-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='embed',
            field=models.TextField(verbose_name='Vkládací kód'),
        ),
    ]
